services:
  - type: web
    name: tfuture
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn TFuture.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DB_NAME
        value: tfuture
      - key: DB_USER
        value: tfuture_user
      - key: DB_PASSWORD
        fromService:
          type: postgres
          name: dpg-d12krrp5pdvs73crgo70-a
          property: password
      - key: DB_HOST
        value: dpg-d12krrp5pdvs73crgo70-a
      - key: DB_PORT
        value: 5432

  - type: postgres
    name: tfuture-db
    plan: free
    ipAllowList: [] 