# Generated by Django 5.1.9 on 2025-06-06 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('client', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('brand-identity', 'Brand & Visual Identity'), ('communication-kits', 'Company Communication Kits'), ('events', 'Events Experience'), ('rollouts', 'Rollouts & Merchandise')], max_length=50)),
                ('subcategory', models.CharField(choices=[('full-brand', 'Full Brand Identity'), ('visual-identity', 'Visual Identity'), ('logofolio', 'Logofolio'), ('company-profiles', 'Company Profiles'), ('presentations', 'Presentations'), ('internal-coms', 'Internal Coms & SOPs'), ('stationery', 'Stationery'), ('social-media', 'Social Media Kits')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
