# Generated by Django 5.1.9 on 2025-06-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('full-brand', 'Full Brand Identity'), ('visual-identity', 'Visual Identity'), ('logofolio', 'Logofolio'), ('company-profiles', 'Company Profiles'), ('presentations', 'Presentations'), ('internal-coms', 'Internal Coms & SOPs'), ('stationery', 'Stationery'), ('social-media', 'Social Media Kits')], max_length=50, null=True),
        ),
    ]
