# Generated by Django 5.1.9 on 2025-09-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('admin', 'Admin')], default='website', help_text='Where this request originated from', max_length=10),
        ),
    ]
