# Generated by Django 5.1.9 on 2025-09-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_service_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(help_text="⚠️ For General Inquiry: slug MUST be 'general-inquiry'", max_length=200, unique=True),
        ),
    ]
