# Generated by Django 5.1.9 on 2025-09-11 12:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_service_slug'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('testimonials', wagtail.fields.StreamField([('testimonial', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Person's name", 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Job title and company', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Short initials for avatar circle', 'max_length': 3, 'required': True}), 3: ('wagtail.blocks.TextBlock', (), {'help_text': 'Testimonial text', 'required': True}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional profile image', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('name', 0), ('role', 1), ('initials', 2), ('quote', 3), ('image', 4)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
