# Generated by Django 5.1.9 on 2025-09-12 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Person's name", max_length=100)),
                ('role', models.CharField(help_text='Job title and company', max_length=100)),
                ('initials', models.CharField(help_text='Short initials for avatar circle', max_length=3)),
                ('quote', models.TextField(help_text='Testimonial text')),
                ('featured', models.BooleanField(default=False, help_text='If selected, this testimonial will appear on the homepage')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, help_text='Optional profile image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
