# Generated by Django 5.1.9 on 2025-09-04 12:35

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('video', 3), ('code', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube/Vimeo link'}), 4: ('wagtail.blocks.TextBlock', (), {'help_text': 'Paste code snippet'})}),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='cms.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['parent__name', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select a category or subcategory from snippets.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='cms.category'),
        ),
    ]
