# Generated by Django 5.1.9 on 2025-09-04 13:52

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_remove_projectpage_subcategory_projectpage_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='client',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='industry',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='hero',
            field=wagtail.fields.StreamField([('hero', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Small label above the headline', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main project headline', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'required': True}), 3: ('wagtail.blocks.ListBlock', (2,), {'help_text': 'Tags shown next to the hero'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.StructBlock', [[('label', 0), ('headline', 1), ('tags', 3), ('hero_image', 4)]], {})}, default=list),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='intro',
            field=wagtail.fields.StreamField([('intro', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Muted subheading', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Intro/context paragraph', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('subheading', 0), ('context', 1)]], {})}, default=list),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_images', to='cms.projectpage'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('muted_subheading', 1), ('rich_text', 2), ('quote', 3), ('image', 4), ('image_with_caption', 6), ('image_grid', 7), ('video_embed', 8), ('two_column', 11), ('stats_grid', 14), ('bulleted_list', 15), ('callout', 16), ('code', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Muted subheading'}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'help_text': 'Add 2-6 images'}), 8: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube/Vimeo link'}), 9: ('wagtail.blocks.TextBlock', (), {'help_text': 'Code'}), 10: ('wagtail.blocks.StreamBlock', [[('rich_text', 2), ('image', 4), ('quote', 3), ('code', 9)]], {'required': False}), 11: ('wagtail.blocks.StructBlock', [[('left', 10), ('right', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {}), 13: ('wagtail.blocks.StructBlock', [[('label', 12), ('value', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'help_text': 'Small set of key stats'}), 15: ('wagtail.blocks.ListBlock', (12,), {}), 16: ('wagtail.blocks.StructBlock', [[('title', 12), ('body', 2)]], {}), 17: ('wagtail.blocks.TextBlock', (), {'help_text': 'Paste code snippet'})}),
        ),
    ]
