# Generated by Django 5.1.9 on 2025-09-11 12:40

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_blogcategory_blogindexpage_blogpage_blogpagetag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this blog on the homepage'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this project on the homepage'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('muted_subheading', 2), ('rich_text', 3), ('quote', 4), ('image', 5), ('image_with_caption', 7), ('image_grid', 8), ('video_embed', 9), ('two_column', 12), ('stats_grid', 15), ('bulleted_list', 16), ('callout', 17), ('code', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Normal subheading (H2 size)'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Muted subheading'}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.blocks.BlockQuoteBlock', (), {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'help_text': 'Add 2-6 images'}), 9: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'YouTube/Vimeo link'}), 10: ('wagtail.blocks.TextBlock', (), {'help_text': 'Code'}), 11: ('wagtail.blocks.StreamBlock', [[('rich_text', 3), ('image', 5), ('quote', 4), ('code', 10)]], {'required': False}), 12: ('wagtail.blocks.StructBlock', [[('left', 11), ('right', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {}), 14: ('wagtail.blocks.StructBlock', [[('label', 13), ('value', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {'help_text': 'Small set of key stats'}), 16: ('wagtail.blocks.ListBlock', (13,), {}), 17: ('wagtail.blocks.StructBlock', [[('title', 13), ('body', 3)]], {}), 18: ('wagtail.blocks.TextBlock', (), {'help_text': 'Paste code snippet'})}),
        ),
    ]
