# Generated by Django 5.1.9 on 2025-09-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_remove_testimonialspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='behance_link',
            field=models.URLField(blank=True, help_text='Optional link to the project on Behance', max_length=255, null=True),
        ),
    ]
