# Generated by Django 5.1.9 on 2025-09-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_projectpage_seo_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='seo_africa_focus',
            field=models.CharField(blank=True, help_text='Africa-specific keywords or phrases for regional SEO (e.g., brand identity design Africa, brand development Africa)', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='seo_brand_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for TFuture Designs brand differentiation and services (e.g., brand architecture, identity systems, corporate branding)', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='seo_industry_differentiator',
            field=models.CharField(blank=True, help_text='Industry-specific terms that differentiate TFuture Designs as brand architects (e.g., strategic brand architecture, professional brand identity systems)', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='seo_kenya_focus',
            field=models.CharField(blank=True, help_text='Kenya-specific keywords or phrases for local SEO (e.g., best brand designers in Kenya, top branding agency in Kenya)', max_length=255),
        ),
    ]
