# Generated by Django 5.1.9 on 2025-09-18 07:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_alter_projectpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectindexpage',
            name='hero_tiles',
            field=wagtail.fields.StreamField([('tile', 15)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('featured', 'Featured'), ('accent', 'Accent')], 'help_text': 'Tile style'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image', 'Image'), ('video', 'Video'), ('icon', 'Icon')], 'help_text': 'Type of media'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Video URL (mp4/webm)', 'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'SVG/PNG icon', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Tile headline', 'required': False}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Tile description', 'required': False}), 7: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Highlight as featured tile', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'CTA button text', 'required': False}), 9: ('wagtail.blocks.URLBlock', (), {'help_text': 'CTA button link', 'required': False}), 10: ('wagtail.blocks.FloatBlock', (), {'help_text': 'Grid left position (%)', 'required': False}), 11: ('wagtail.blocks.FloatBlock', (), {'help_text': 'Grid top position (%)', 'required': False}), 12: ('wagtail.blocks.FloatBlock', (), {'help_text': 'Tile width (%)', 'required': False}), 13: ('wagtail.blocks.FloatBlock', (), {'help_text': 'Tile height (%)', 'required': False}), 14: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Z-index for stacking', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('tile_type', 0), ('media_type', 1), ('image', 2), ('video_url', 3), ('icon', 4), ('title', 5), ('description', 6), ('featured', 7), ('cta_text', 8), ('cta_url', 9), ('left', 10), ('top', 11), ('width', 12), ('height', 13), ('z_index', 14)]], {})}, default=list, verbose_name='Creative Wall Hero Tiles'),
        ),
    ]
