# Generated by Django 5.1.9 on 2025-09-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_projectindexpage_hero_tiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectindexpage',
            name='hero_tiles',
        ),
    ]
