# Generated by Django 5.1.9 on 2025-12-15 02:49

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_faqitem'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandDiscoveryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text to display at the top of the form')),
                ('form_questions', wagtail.fields.StreamField([('question', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Question label (e.g., 'What is your company size?')", 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Short Text'), ('textarea', 'Long Text'), ('email', 'Email'), ('phone', 'Phone Number'), ('number', 'Number'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox')], 'help_text': 'Select the input type for this question'}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Is this field required?', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Optional helper text below the label', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': "For dropdown/checkbox: comma-separated options (e.g., 'Option 1, Option 2, Option 3')", 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('label', 0), ('field_type', 1), ('required', 2), ('help_text', 3), ('options', 4)]], {})}, help_text='Add form questions here. Reorder as needed.')),
                ('thank_you_message', wagtail.fields.RichTextField(blank=True, default="<p>Thank you for your inquiry! We'll review your information and get back to you shortly.</p>", help_text='Message shown after successful form submission')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BrandDiscoverySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_name', models.CharField(help_text='Name of business representative', max_length=200)),
                ('business_name', models.CharField(help_text='Name of the business', max_length=200)),
                ('email', models.EmailField(help_text='Email for confirmation', max_length=254)),
                ('phone', models.CharField(help_text='Phone number', max_length=30)),
                ('additional_responses', models.JSONField(blank=True, default=dict, help_text='Additional form responses stored as JSON')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='new', help_text='Status of this inquiry', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for this submission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand Discovery Submission',
                'verbose_name_plural': 'Brand Discovery Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
