# Generated by Django 5.1.9 on 2025-12-15 04:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_branddiscoverypage_branddiscoverysubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branddiscoverypage',
            name='form_questions',
        ),
        migrations.AddField(
            model_name='branddiscoverypage',
            name='form_sections',
            field=wagtail.fields.StreamField([('section', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Title for this section (e.g., 'Detailed Overview')", 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Optional description text for the section', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "Question label (e.g., 'What is your company size?')", 'required': True}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Short Text'), ('textarea', 'Long Text'), ('email', 'Email'), ('phone', 'Phone Number'), ('number', 'Number'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox')], 'help_text': 'Select the input type for this question'}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Is this field required?', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Optional helper text below the label', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': "For dropdown/checkbox: comma-separated options (e.g., 'Option 1, Option 2, Option 3')", 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 2), ('field_type', 3), ('required', 4), ('help_text', 5), ('options', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'help_text': 'Add questions for this section'}), 9: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('section_description', 1), ('questions', 8)]], {})}, help_text='Add form sections with questions. Reorder as needed.'),
        ),
    ]
