# Generated by Django 5.1.9 on 2025-12-22 21:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_privacypolicypage_updates_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicypage',
            name='clauses',
            field=wagtail.fields.StreamField([('clause', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Clause title', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ul', 'ol', 'hr', 'code'], 'help_text': 'Clause content', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('body', 1)]], {'icon': 'form', 'label': 'Clause'})}, help_text='Add privacy policy clauses (title + content)'),
        ),
    ]
