# Generated by Django 5.1.9 on 2025-12-22 22:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_termsofservicepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicypage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Brief description shown below the title (optional)'),
        ),
        migrations.AddField(
            model_name='termsofservicepage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Brief description shown below the title (optional)'),
        ),
    ]
