# Generated by Django 5.1.9 on 2025-12-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0026_privacypolicypage_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectpage",
            name="show_hero_image",
            field=models.BooleanField(
                default=True,
                help_text="Show the hero image on the project detail page (still used for thumbnails and meta images).",
            ),
        ),
    ]
