# Generated by Django 5.1.9 on 2026-01-03 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_projectpage_show_hero_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='show_featured_image',
            field=models.BooleanField(default=True, help_text='Display featured image on the blog page (always shown in previews)'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='featured_image',
            field=models.ForeignKey(help_text='Required - used for previews and social sharing', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
    ]
