# Generated by Django 5.1.9 on 2026-01-10 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_remove_excerpt_and_update_featured_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='featured_image',
            field=models.ForeignKey(help_text='Required - used for previews and social sharing', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
    ]
