# Generated by Django 5.1.9 on 2026-02-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_alter_blogpage_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='intro',
            field=models.TextField(blank=True, help_text='Brief summary shown in article previews and previews'),
        ),
    ]
